package com.ufpa.movieticket.model;
// Generated 07/04/2017 10:51:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartaocredId generated by hbm2java
 */
@Embeddable
public class CartaocredId  implements java.io.Serializable {


     private int pkCartaocred;
     private int fkPessoa;

    public CartaocredId() {
    }

    public CartaocredId(int pkCartaocred, int fkPessoa) {
       this.pkCartaocred = pkCartaocred;
       this.fkPessoa = fkPessoa;
    }
   


    @Column(name="pk_cartaocred", nullable=false)
    public int getPkCartaocred() {
        return this.pkCartaocred;
    }
    
    public void setPkCartaocred(int pkCartaocred) {
        this.pkCartaocred = pkCartaocred;
    }


    @Column(name="fk_pessoa", nullable=false)
    public int getFkPessoa() {
        return this.fkPessoa;
    }
    
    public void setFkPessoa(int fkPessoa) {
        this.fkPessoa = fkPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartaocredId) ) return false;
		 CartaocredId castOther = ( CartaocredId ) other; 
         
		 return (this.getPkCartaocred()==castOther.getPkCartaocred())
 && (this.getFkPessoa()==castOther.getFkPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkCartaocred();
         result = 37 * result + this.getFkPessoa();
         return result;
   }   


}


