package com.ufpa.movieticket.model;
// Generated 07/04/2017 10:51:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="bd_sistemaCinema"
)
public class Compra  implements java.io.Serializable {


     private CompraId id;
     private Cartaocred cartaocred;
     private Exibicao exibicao;
     private Date dataCompra;
     private int qtdIngresso;

    public Compra() {
    }

    public Compra(CompraId id, Cartaocred cartaocred, Exibicao exibicao, Date dataCompra, int qtdIngresso) {
       this.id = id;
       this.cartaocred = cartaocred;
       this.exibicao = exibicao;
       this.dataCompra = dataCompra;
       this.qtdIngresso = qtdIngresso;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkCompra", column=@Column(name="pk_compra", nullable=false) ), 
        @AttributeOverride(name="fkExibicao", column=@Column(name="fk_exibicao", nullable=false) ), 
        @AttributeOverride(name="fkCartaocred", column=@Column(name="fk_cartaocred", nullable=false) ), 
        @AttributeOverride(name="cartaocredFkPessoa", column=@Column(name="cartaocred_fk_pessoa", nullable=false) ) } )
    public CompraId getId() {
        return this.id;
    }
    
    public void setId(CompraId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="fk_cartaocred", referencedColumnName="pk_cartaocred", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="cartaocred_fk_pessoa", referencedColumnName="fk_pessoa", nullable=false, insertable=false, updatable=false) } )
    public Cartaocred getCartaocred() {
        return this.cartaocred;
    }
    
    public void setCartaocred(Cartaocred cartaocred) {
        this.cartaocred = cartaocred;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_exibicao", nullable=false, insertable=false, updatable=false)
    public Exibicao getExibicao() {
        return this.exibicao;
    }
    
    public void setExibicao(Exibicao exibicao) {
        this.exibicao = exibicao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_compra", nullable=false, length=19)
    public Date getDataCompra() {
        return this.dataCompra;
    }
    
    public void setDataCompra(Date dataCompra) {
        this.dataCompra = dataCompra;
    }

    
    @Column(name="qtd_ingresso", nullable=false)
    public int getQtdIngresso() {
        return this.qtdIngresso;
    }
    
    public void setQtdIngresso(int qtdIngresso) {
        this.qtdIngresso = qtdIngresso;
    }




}


