package com.ufpa.movieticket.model;
// Generated 07/04/2017 10:51:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exibicao generated by hbm2java
 */
@Entity
@Table(name="exibicao"
    ,catalog="bd_sistemaCinema"
)
public class Exibicao  implements java.io.Serializable {


     private Integer pkExibicao;
     private Cinema cinema;
     private Filme filme;
     private long valorExibcao;
     private Date dataExibicao;
     private Date horaExibicao;
     private String sala;
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Exibicao() {
    }

	
    public Exibicao(Cinema cinema, Filme filme, long valorExibcao, Date dataExibicao, Date horaExibicao, String sala) {
        this.cinema = cinema;
        this.filme = filme;
        this.valorExibcao = valorExibcao;
        this.dataExibicao = dataExibicao;
        this.horaExibicao = horaExibicao;
        this.sala = sala;
    }
    public Exibicao(Cinema cinema, Filme filme, long valorExibcao, Date dataExibicao, Date horaExibicao, String sala, Set<Compra> compras) {
       this.cinema = cinema;
       this.filme = filme;
       this.valorExibcao = valorExibcao;
       this.dataExibicao = dataExibicao;
       this.horaExibicao = horaExibicao;
       this.sala = sala;
       this.compras = compras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_exibicao", unique=true, nullable=false)
    public Integer getPkExibicao() {
        return this.pkExibicao;
    }
    
    public void setPkExibicao(Integer pkExibicao) {
        this.pkExibicao = pkExibicao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cinema", nullable=false)
    public Cinema getCinema() {
        return this.cinema;
    }
    
    public void setCinema(Cinema cinema) {
        this.cinema = cinema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_filme", nullable=false)
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }

    
    @Column(name="valor_exibcao", nullable=false, precision=10, scale=0)
    public long getValorExibcao() {
        return this.valorExibcao;
    }
    
    public void setValorExibcao(long valorExibcao) {
        this.valorExibcao = valorExibcao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_exibicao", nullable=false, length=10)
    public Date getDataExibicao() {
        return this.dataExibicao;
    }
    
    public void setDataExibicao(Date dataExibicao) {
        this.dataExibicao = dataExibicao;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_exibicao", nullable=false, length=8)
    public Date getHoraExibicao() {
        return this.horaExibicao;
    }
    
    public void setHoraExibicao(Date horaExibicao) {
        this.horaExibicao = horaExibicao;
    }

    
    @Column(name="sala", nullable=false, length=50)
    public String getSala() {
        return this.sala;
    }
    
    public void setSala(String sala) {
        this.sala = sala;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exibicao")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


