package com.ufpa.movieticket.model;
// Generated 07/04/2017 10:51:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Filme generated by hbm2java
 */
@Entity
@Table(name="filme"
    ,catalog="bd_sistemaCinema"
)
public class Filme  implements java.io.Serializable {


     private Integer pkFilme;
     private String nomeFilme;
     private String genero;
     private String sinopse;
     private Date anoLancamento;
     private String classificacao;
     private Set<Exibicao> exibicaos = new HashSet<Exibicao>(0);

    public Filme() {
    }

	
    public Filme(String nomeFilme, String genero, String sinopse, Date anoLancamento, String classificacao) {
        this.nomeFilme = nomeFilme;
        this.genero = genero;
        this.sinopse = sinopse;
        this.anoLancamento = anoLancamento;
        this.classificacao = classificacao;
    }
    public Filme(String nomeFilme, String genero, String sinopse, Date anoLancamento, String classificacao, Set<Exibicao> exibicaos) {
       this.nomeFilme = nomeFilme;
       this.genero = genero;
       this.sinopse = sinopse;
       this.anoLancamento = anoLancamento;
       this.classificacao = classificacao;
       this.exibicaos = exibicaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_filme", unique=true, nullable=false)
    public Integer getPkFilme() {
        return this.pkFilme;
    }
    
    public void setPkFilme(Integer pkFilme) {
        this.pkFilme = pkFilme;
    }

    
    @Column(name="nome_filme", nullable=false, length=100)
    public String getNomeFilme() {
        return this.nomeFilme;
    }
    
    public void setNomeFilme(String nomeFilme) {
        this.nomeFilme = nomeFilme;
    }

    
    @Column(name="genero", nullable=false, length=100)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="sinopse", nullable=false, length=250)
    public String getSinopse() {
        return this.sinopse;
    }
    
    public void setSinopse(String sinopse) {
        this.sinopse = sinopse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ano_lancamento", nullable=false, length=10)
    public Date getAnoLancamento() {
        return this.anoLancamento;
    }
    
    public void setAnoLancamento(Date anoLancamento) {
        this.anoLancamento = anoLancamento;
    }

    
    @Column(name="classificacao", nullable=false, length=16)
    public String getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(String classificacao) {
        this.classificacao = classificacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filme")
    public Set<Exibicao> getExibicaos() {
        return this.exibicaos;
    }
    
    public void setExibicaos(Set<Exibicao> exibicaos) {
        this.exibicaos = exibicaos;
    }




}


