package com.ufpa.movieticket.model;
// Generated 07/04/2017 10:51:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="bd_sistemaCinema"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Pessoa  implements java.io.Serializable {


     private Integer pkPessoa;
     private String cpf;
     private String nomePessoa;
     private String email;
     private String nikePessoa;
     private String senha;
     private String tipoPessoa;
     private Set<Cartaocred> cartaocreds = new HashSet<Cartaocred>(0);

    public Pessoa() {
    }

	
    public Pessoa(String cpf, String nomePessoa, String email, String nikePessoa, String senha, String tipoPessoa) {
        this.cpf = cpf;
        this.nomePessoa = nomePessoa;
        this.email = email;
        this.nikePessoa = nikePessoa;
        this.senha = senha;
        this.tipoPessoa = tipoPessoa;
    }
    public Pessoa(String cpf, String nomePessoa, String email, String nikePessoa, String senha, String tipoPessoa, Set<Cartaocred> cartaocreds) {
       this.cpf = cpf;
       this.nomePessoa = nomePessoa;
       this.email = email;
       this.nikePessoa = nikePessoa;
       this.senha = senha;
       this.tipoPessoa = tipoPessoa;
       this.cartaocreds = cartaocreds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_pessoa", unique=true, nullable=false)
    public Integer getPkPessoa() {
        return this.pkPessoa;
    }
    
    public void setPkPessoa(Integer pkPessoa) {
        this.pkPessoa = pkPessoa;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="nome_pessoa", nullable=false, length=100)
    public String getNomePessoa() {
        return this.nomePessoa;
    }
    
    public void setNomePessoa(String nomePessoa) {
        this.nomePessoa = nomePessoa;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nike_pessoa", nullable=false, length=50)
    public String getNikePessoa() {
        return this.nikePessoa;
    }
    
    public void setNikePessoa(String nikePessoa) {
        this.nikePessoa = nikePessoa;
    }

    
    @Column(name="senha", nullable=false, length=100)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="tipo_pessoa", nullable=false, length=7)
    public String getTipoPessoa() {
        return this.tipoPessoa;
    }
    
    public void setTipoPessoa(String tipoPessoa) {
        this.tipoPessoa = tipoPessoa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Cartaocred> getCartaocreds() {
        return this.cartaocreds;
    }
    
    public void setCartaocreds(Set<Cartaocred> cartaocreds) {
        this.cartaocreds = cartaocreds;
    }




}


