package com.ufpa.movieticket.model;
// Generated 25/03/2017 21:20:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cinema generated by hbm2java
 */
@Entity
@Table(name="cinema"
    ,catalog="bd_sistemaCinema"
)
public class Cinema  implements java.io.Serializable {


     private Integer pkCinema;
     private Cidade cidade;
     private String nomeCinema;
     private Set<Exibicao> exibicaos = new HashSet<Exibicao>(0);

    public Cinema() {
    }

	
    public Cinema(Cidade cidade, String nomeCinema) {
        this.cidade = cidade;
        this.nomeCinema = nomeCinema;
    }
    public Cinema(Cidade cidade, String nomeCinema, Set<Exibicao> exibicaos) {
       this.cidade = cidade;
       this.nomeCinema = nomeCinema;
       this.exibicaos = exibicaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_cinema", unique=true, nullable=false)
    public Integer getPkCinema() {
        return this.pkCinema;
    }
    
    public void setPkCinema(Integer pkCinema) {
        this.pkCinema = pkCinema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cidade", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="nome_cinema", nullable=false, length=45)
    public String getNomeCinema() {
        return this.nomeCinema;
    }
    
    public void setNomeCinema(String nomeCinema) {
        this.nomeCinema = nomeCinema;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cinema")
    public Set<Exibicao> getExibicaos() {
        return this.exibicaos;
    }
    
    public void setExibicaos(Set<Exibicao> exibicaos) {
        this.exibicaos = exibicaos;
    }




}


