package com.ufpa.movieticket.model;
// Generated 25/03/2017 21:20:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompraId generated by hbm2java
 */
@Embeddable
public class CompraId  implements java.io.Serializable {


     private int pkCompra;
     private int fkExibicao;
     private int fkCartaocred;
     private int cartaocredFkPessoa;

    public CompraId() {
    }

    public CompraId(int pkCompra, int fkExibicao, int fkCartaocred, int cartaocredFkPessoa) {
       this.pkCompra = pkCompra;
       this.fkExibicao = fkExibicao;
       this.fkCartaocred = fkCartaocred;
       this.cartaocredFkPessoa = cartaocredFkPessoa;
    }
   


    @Column(name="pk_compra", nullable=false)
    public int getPkCompra() {
        return this.pkCompra;
    }
    
    public void setPkCompra(int pkCompra) {
        this.pkCompra = pkCompra;
    }


    @Column(name="fk_exibicao", nullable=false)
    public int getFkExibicao() {
        return this.fkExibicao;
    }
    
    public void setFkExibicao(int fkExibicao) {
        this.fkExibicao = fkExibicao;
    }


    @Column(name="fk_cartaocred", nullable=false)
    public int getFkCartaocred() {
        return this.fkCartaocred;
    }
    
    public void setFkCartaocred(int fkCartaocred) {
        this.fkCartaocred = fkCartaocred;
    }


    @Column(name="cartaocred_fk_pessoa", nullable=false)
    public int getCartaocredFkPessoa() {
        return this.cartaocredFkPessoa;
    }
    
    public void setCartaocredFkPessoa(int cartaocredFkPessoa) {
        this.cartaocredFkPessoa = cartaocredFkPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompraId) ) return false;
		 CompraId castOther = ( CompraId ) other; 
         
		 return (this.getPkCompra()==castOther.getPkCompra())
 && (this.getFkExibicao()==castOther.getFkExibicao())
 && (this.getFkCartaocred()==castOther.getFkCartaocred())
 && (this.getCartaocredFkPessoa()==castOther.getCartaocredFkPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkCompra();
         result = 37 * result + this.getFkExibicao();
         result = 37 * result + this.getFkCartaocred();
         result = 37 * result + this.getCartaocredFkPessoa();
         return result;
   }   


}


