-- MySQL Script generated by MySQL Workbench
-- Sáb 25 Mar 2017 13:35:52 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sistemaCinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_sistemaCinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sistemaCinema` DEFAULT CHARACTER SET utf8 ;
USE `bd_sistemaCinema` ;

-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`cidade` (
  `pk_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NOT NULL,
  `uf` SET('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RN', 'RS', 'RJ', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
  PRIMARY KEY (`pk_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`cinema` (
  `pk_cinema` INT NOT NULL AUTO_INCREMENT,
  `nome_cinema` VARCHAR(45) NOT NULL,
  `fk_cidade` INT NOT NULL,
  PRIMARY KEY (`pk_cinema`),
  INDEX `fk_cinema_cidade_idx` (`fk_cidade` ASC),
  CONSTRAINT `fk_cinema_cidade`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `bd_sistemaCinema`.`cidade` (`pk_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`filme` (
  `pk_filme` INT NOT NULL AUTO_INCREMENT,
  `nome_filme` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `sinopse` VARCHAR(250) NOT NULL,
  `ano_lancamento` DATE NOT NULL,
  `classificacao` SET('L', '10', '12', '14', '16', '18') NOT NULL,
  PRIMARY KEY (`pk_filme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`exibicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`exibicao` (
  `pk_exibicao` INT NOT NULL AUTO_INCREMENT,
  `valor_exibcao` DECIMAL NOT NULL,
  `data_exibicao` DATE NOT NULL,
  `hora_exibicao` TIME(6) NOT NULL,
  `sala` VARCHAR(50) NOT NULL,
  `fk_cinema` INT NOT NULL,
  `fk_filme` INT NOT NULL,
  PRIMARY KEY (`pk_exibicao`),
  INDEX `fk_exibicao_cinema1_idx` (`fk_cinema` ASC),
  INDEX `fk_exibicao_filme1_idx` (`fk_filme` ASC),
  CONSTRAINT `fk_exibicao_cinema1`
    FOREIGN KEY (`fk_cinema`)
    REFERENCES `bd_sistemaCinema`.`cinema` (`pk_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exibicao_filme1`
    FOREIGN KEY (`fk_filme`)
    REFERENCES `bd_sistemaCinema`.`filme` (`pk_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`pessoa` (
  `pk_pessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome_pessoa` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nike_pessoa` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipo_pessoa` SET('cli', 'adm') NOT NULL,
  PRIMARY KEY (`pk_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`cartaocred`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`cartaocred` (
  `pk_cartaocred` INT NOT NULL AUTO_INCREMENT,
  `fk_pessoa` INT NOT NULL,
  `num_cartao` BIGINT(13) NOT NULL,
  `cod_seguranca` INT(3) NOT NULL,
  PRIMARY KEY (`pk_cartaocred`, `fk_pessoa`),
  INDEX `fk_cartaocred_pessoa1_idx` (`fk_pessoa` ASC),
  CONSTRAINT `fk_cartaocred_pessoa1`
    FOREIGN KEY (`fk_pessoa`)
    REFERENCES `bd_sistemaCinema`.`pessoa` (`pk_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistemaCinema`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistemaCinema`.`compra` (
  `pk_compra` INT NOT NULL AUTO_INCREMENT,
  `data_compra` TIMESTAMP(6) NOT NULL,
  `qtd_ingresso` INT(3) NOT NULL,
  `fk_exibicao` INT NOT NULL,
  `fk_cartaocred` INT NOT NULL,
  `cartaocred_fk_pessoa` INT NOT NULL,
  PRIMARY KEY (`pk_compra`, `fk_exibicao`, `fk_cartaocred`, `cartaocred_fk_pessoa`),
  INDEX `fk_compra_exibicao1_idx` (`fk_exibicao` ASC),
  INDEX `fk_compra_cartaocred1_idx` (`fk_cartaocred` ASC, `cartaocred_fk_pessoa` ASC),
  CONSTRAINT `fk_compra_exibicao1`
    FOREIGN KEY (`fk_exibicao`)
    REFERENCES `bd_sistemaCinema`.`exibicao` (`pk_exibicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_cartaocred1`
    FOREIGN KEY (`fk_cartaocred` , `cartaocred_fk_pessoa`)
    REFERENCES `bd_sistemaCinema`.`cartaocred` (`pk_cartaocred` , `fk_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
